networks:
  ai_network-01:
    driver: bridge

services:
  f5-tts-01:
    image: f5-tts:1.0
    container_name: f5-tts-01
    restart: always
    runtime: nvidia
    privileged: true
    volumes:
      - d:/AI/F5-TTS/results01:/code/results
      - d:/AI/F5-TTS/error01:/code/error
      - d:/AI/F5-TTS/logs01:/code/logs
    environment:
      - TQDM_DISABLE=1 # 全局关闭进度条显示
      - PYTHONUNBUFFERED=1 # 取消标准输出缓冲
      - CUDA_VISIBLE_DEVICES=2
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:1024
      - ASR_URL=http://host.docker.internal:17868/api/v1/asr
    tty: true  # 分配伪终端
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    shm_size: '32g'
    ports:
      - '19988:9988'
    command: python /code/src/f5_tts/infer/infer_fastapi.py
    networks:
      - ai_network-01
