networks:
  ai_network:
    driver: bridge

services:
  f5-tts:
    image: f5-tts:1.0
    container_name: f5-tts
    restart: always
    runtime: nvidia
    privileged: true
    volumes:
      - d:/AI/F5-TTS/results:/code/results
      - d:/AI/F5-TTS/error:/code/error
      - d:/AI/F5-TTS/logs:/code/logs
    environment:
      - TQDM_DISABLE=1 # 全局关闭进度条显示
      - PYTHONUNBUFFERED=1 # 取消标准输出缓冲
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:1024
    tty: true  # 分配伪终端
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    shm_size: '32g'
    ports:
      - '9988:9988'
    command: python /code/src/f5_tts/infer/infer_fastapi.py
    networks:
      - ai_network
